Unit tests for driver handling methods
MAFIN-Squad/mafin-webui-selenium pull request #49
Opened 2023-06-14 18:13 UTC by ValiantsinSerada

2023-06-14 23:58 UTC, Molnix888 commented
Please, check the failing unit tests

2023-07-10 19:55 UTC, Molnix888 requested changes

2023-07-10 19:55 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +            Assert.True(extractedFieldValue != null);
Maybe replace with FluentAssertions?

2023-07-10 19:55 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/Strategy/DriverMappingTests.cs
> +            webConfiguration.DriverType = driverType;
Minor one: I believe, you can define DriverType at the initialization to slightly simplify things.

2023-07-10 19:55 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +            List<string> arguments = new List<string>() { Guid.NewGuid().ToString(), Guid.NewGuid().ToString() };
Minor: I'd go with using AutoFixture for random values generation for consistency. Might be overkill to generate strings butt would be really helpful for complex stuff like generating fake data in models.
Please, see [REST API repo](https://github.com/MAFIN-Squad/mafin-webapi-rest/blob/main/tests/Mafin.Web.Api.Rest.Tests.Unit/Authentication/BasicAuthHandlerTests.cs) for reference.

2023-07-10 19:55 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +    public class FakeOptions : DriverOptions
Technically, that's a Stub though :)
I'd also probably move it out to Stubs namespace just in case.

2023-07-12 11:15 UTC, ValiantsinSerada commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +            Assert.True(extractedFieldValue != null);
Replaced bu FluentAsserttions code

2023-07-12 11:16 UTC, ValiantsinSerada commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/Strategy/DriverMappingTests.cs
> +            webConfiguration.DriverType = driverType;
I don't see simplifying for this action.

2023-07-12 11:16 UTC, ValiantsinSerada commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +            List<string> arguments = new List<string>() { Guid.NewGuid().ToString(), Guid.NewGuid().ToString() };
Autofixture data generationa added

2023-07-12 11:17 UTC, ValiantsinSerada commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/DriverOptionsExtensionsTests.cs
> +    public class FakeOptions : DriverOptions
Moved to Stubs

2023-07-14 00:55 UTC, Molnix888 approved these changes

2023-07-14 00:56 UTC, merged