Bahdan serabrakou/screenshoter
MAFIN-Squad/mafin-webui-selenium pull request #84
Opened 2023-08-16 11:49 UTC by BahdanSerabrakou

2023-08-16 11:57 UTC, ValiantsinSerada submitted a review, later dismissed

2023-08-26 15:37 UTC, Molnix888 requested changes

2023-08-26 15:37 UTC, Molnix888 commented on src/Mafin.Web.UI.Selenium/Mafin.Web.UI.Selenium.csproj
> +    <PackageReference Include="NUnit" />
Let's provide uour users with the flexibility of choosing test runner on their own. We shouldn't have a hard dependency on NUnit.

2023-08-26 15:37 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
> +    <Nullable>warnings</Nullable>
Could you please elaborate why need for the flag?

2023-08-26 15:37 UTC, Molnix888 commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
> +    <Folder Include="TestResults\" />
Do we need this folder explicitly?

2023-08-30 09:46 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="Selenium.WebDriver.Extensions" Version="4.1.0" />
Fixed

2023-09-07 11:24 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="Noksa.WebDriver.ScreenshotsExtensions" Version="0.1.5.4" />
Fixed

2023-09-07 11:30 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="Selenium.WebDriver.Extensions" Version="4.1.0" />
Fixed

2023-09-07 11:36 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/ScreenshotUtility.cs
> +namespace Mafin.Web.UI.Selenium.Utilities
Fixed

2023-09-07 11:38 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Mafin.Web.UI.Selenium.csproj
> +    <PackageReference Include="NUnit" />
Fixed

2023-09-07 11:38 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
> +    <Folder Include="TestResults\" />
Fixed

2023-09-07 11:39 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
> +    <Nullable>warnings</Nullable>
Fixed

2023-09-07 11:39 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/ScreenshotUtility.cs
> +                Directory.CreateDirectory(screenshotDirectory);
Fixed

2023-09-07 11:45 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/ScreenshotUtility.cs
> +    public static class ScreenshotUtility
Fixed

2023-09-12 11:53 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="System.Drawing.Common" Version="7.0.0" />
Fixed

2023-09-14 06:47 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="Noksa.WebDriver.ScreenshotsExtensions" Version="0.1.5.4" />
Fixed

2023-09-16 19:04 UTC, Molnix888 commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +using ImageMagick;
I'm wondering if both fullscreenshot and element screenshot actually possible to be created using only single additional dependency: either ImageMagick or SkiaSharp. On the first sight seems both should be capable of doing so, so I'm thinking whether we should try.

2023-09-19 13:55 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Utilities/DriverScreenshotExtensionsTests.cs
> +namespace Mafin.Web.UI.Selenium.Tests.Unit.Utilities
Fixed

2023-09-21 06:55 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="SkiaSharp" Version="2.88.5" />
Thanks!

2023-09-21 06:55 UTC, BahdanSerabrakou commented on Directory.Packages.props
> +    <PackageVersion Include="Magick.NET-Q16-AnyCPU" Version="13.2.0" />
Thanks!

2023-09-21 06:57 UTC, BahdanSerabrakou commented on examples/Mafin.Web.UI.Selenium.Example/Mafin.Web.UI.Selenium.Example.csproj
> +    <PackageReference Include="SkiaSharp" />
Fixed

2023-09-21 06:57 UTC, BahdanSerabrakou commented on examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Web.UI.Selenium.YapomlExample.csproj
> +    <PackageReference Include="Selenium.Support" />
Fixed

2023-09-21 07:01 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
> +    <PackageReference Include="SkiaSharp" />
Fixed

2023-09-22 12:33 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Enums/ScreenshotType.cs
> +    DefaultScreen
Fixed

2023-09-22 12:34 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Enums/ScreenshotType.cs
> +namespace Mafin.Web.UI.Selenium.Enums;
Fixed

2023-09-22 12:42 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +namespace Mafin.Web.UI.Selenium.Utilities;
Fixed

2023-09-22 12:43 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +public static class DriverScreenshotExtensions
Fixed

2023-09-22 12:50 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Utilities/DriverScreenshotExtensionsTests.cs
> +        // Arrange
Fixed

2023-09-22 12:51 UTC, BahdanSerabrakou commented on tests/Mafin.Web.UI.Selenium.Tests.Unit/Utilities/DriverScreenshotExtensionsTests.cs
> +    public void TakeFlexibleScreenshot_WhenTakeDefaultScreenshot_ShouldSaveScreenshot()
Fixed

2023-09-22 12:52 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +        var screenshotCollection = new MagickImageCollection();
Fixed

2023-09-22 12:55 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +    private static void TakeFullPageScreenshot(this IWebDriver driver, string screenshotFilePath = "", params By[] elementsLocatorToHide)
Fixed

2023-09-22 12:59 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Enums/ScreenshotType.cs
> +public enum ScreenshotType
Fixed

2023-09-22 13:43 UTC, BahdanSerabrakou commented on src/Mafin.Web.UI.Selenium/Utilities/DriverScreenshotExtensions.cs
> +    public static void TakeFlexibleScreenshot(this IWebDriver driver, ScreenshotType screenshotType = ScreenshotType.DefaultScreen, IWebElement? element = null, string screenshotName = "", string scr
Fixed
Fixed

2023-09-22 23:56 UTC, Molnix888 approved these changes

2023-09-22 23:57 UTC, merged